version: '2.3'

networks:
  quarkus-json-exporter-network:
#    external: true
#    name: quarkus-json-exporter-network

services:
  quarkus-json-exporter:
    env_file:
      - .env
    image: ${DOCKER_REGISTRY}weigo/quarkus_json_exporter
    container_name: quarkus-json-exporter
    volumes:
      - ./doc/examples/application.yml:/deployments/config/application.yml
    ports:
      - "7979:7978"
    #    environment:
    #      - QUARKUS_HTTP_PORT=7978
    networks:
      - quarkus-json-exporter-network
