quarkus:
  http:
    port: 7979
"%test":
  quarkus:
    http:
      test-port: -1
  exporter:
    modules:
      - name: default
        metrics:
          - name: simple_value
            help: simple value
            path: $.value
      - name: nested_structured_as_several_metrics_using_value
        metrics:
          - name: nested_structured
            help: nested structured
            path: $.data.service1
            labels:
              service: service1
          - name: nested_structured
            help: nested structured
            path: $.data.service2
            type: value
            labels:
              service: service2
      - name: nested_structured_as_several_metrics_using_object
        metrics:
          - name: nested_structured
            help: nested structured
            path: $.data
            type: object
            labels:
              service: service1
            values:
              service: $.service1
          - name: nested_structured
            help: nested structured
            path: $.data
            type: object
            labels:
              service: service2
            values:
              service: $.service2
      - name: health
        metrics:
          - name: health
            help: Health Status
            path: $[?(@.status=="UP")]
            labels:
              x: y
      - name: string_value_mapper
        metrics:
          - name: health_status
            help: Health Status
            path: $.value1
            mapper:
              type: STRING_AS_VALUE
              mappings:
                - key: UP
                  value: 1
                - key: DOWN
                  value: 0
      - name: string_value_mapper_1
        metrics:
          - name: health_status
            help: Health Status
            path: $.value2
            mapper:
              type: STRING_AS_VALUE
              mappings:
                - key: UP
                  value: 1
                - key: DOWN
                  value: 0
